translate.go, wdte.go, wdte_test.go
Part of #14.
This is a potentially breaking change, as it will break any code which has functions with arguments that have the same ID as an import.
=> wdte: Make Modules Act like Functions

translate.go, wdte.go, wdte_test.go
Closes #38.
This *vastly* cleans up the way subscopes work. It's pretty similar to the layout specified in #38, but with a few tweaks and changes. It also reverses chains to allow each element of the chain to create a new frame for the subsequent ones. This makes slots work properly, instead of using the horrible 'workaround' that it was using before.
Unfortunately, this breaks memoization of recursive functions for some reason. It may also break `stream.range`, but I'm not sure yet.
=> wdte: Overhaul frames and scopes.

std/strings/format.go, wdte.go, wdte_test.go
Turns out it breaks things. Like memoization.
=> multiple: Don't overwrite elements of `args` in function calls.

wdte.go, wdte_test.go
Memoization doesn't work, but it actually doesn't quite work for 'normal' functions. Might need to tweak a few things to get it working right.
Closes #35.
=> wdte: Fix lambda recursion.

std/stream/middle.go
Woops. I typed it but didn't save it before committing.
=> std/stream: Add missing comment.

std/stream/middle.go, std/stream/start.go, wdte.go, wdte_test.go
Cleaner and, probably, more memory efficient.
=> stream: Change `flatMap` to use streams instead of arrays.

std/arrays/arrays.go, std/import.go, std/io/file/file.go, std/io/io.go, std/math/math.go, std/std.go, std/stream/stream.go, std/strings/strings.go, wdte_test.go
Inverts imports to work the way the `image` package does in the Go standard library. Standard library imports now register themselves with `std.Import` in an `init()` function, meaning that you can selectively import parts of the standard library more easily. For example, if you want to import just the `io` package, just import the following in Go code:
```go
"github.com/DeedleFake/wdte/std"
_ "github.com/DeedleFake/wdte/std/io"
```
Then use `std.Import` as usual.
=> std: Invert imports.

wdte.go, wdte_test.go
=> wdte: Call the last element of a compound again with arguments if any are given.

translate.go, wdte_test.go
=> wdte: Don't wrap argumentless `let`s in Lambdas.

std/arrays/arrays.go, std/io/file/file.go, std/io/io.go, std/math/math.go, std/std.go, std/stream/end.go, std/stream/middle.go, std/stream/start.go, std/stream/stream.go, std/strings/format.go, std/strings/strings.go, wdte.go, wdte_test.go
All documentation for WDTE functions is now in the form
```go
// <name> is a WDTE function with the following signatures:
//
//    <name> some args
//    (<name> some) args
//
// <description>
```
This hopefully makes it much, much easier to see at a glance how to use each function.
Along with this, a number of tweaks have been made:
* `std/stream`: Range now handles negative step values.
* `wdte`: A few tweaks to the `Scope` API.
=> multiple: Rework basically all the standard library documentation plus a few other tweaks.

std/std.go, wdte.go, wdte_test.go
Closes #85. Unlike that issues specifies, however, the bounds creation is done in `objectify` and `sub`, rather than in `Scope.Collect()`.
=> multiple: Add support for using scopes as objects.

std/stream/middle.go, wdte.go, wdte_test.go
=> wdte: Call function of `Expr` before passing it arguments.

README.md
* Remove GopherJS references and replace with WebAssembly.
* Add syntax highlighting to example.
=> wdte: Some Minor README Tweaks

go.mod, go.sum, std/arrays/arrays.go, std/io/file/file.go, std/io/io.go, std/std.go, std/stream/end.go, std/stream/stream.go, types.go, wdte.go
Closes #136.
It works a bit differently than in #136. The initial implementation was pretty much as that issue gave as an example, but that quickly ran into a few issues. For one thing, `std/io/file`'s `File` type can act as a `Reader` and a `Writer`, as well as being itself a `File`. Simply returning a string identifier was not sufficient for handling all of these cases. Instead, it now works similarly to a Go type assertion, giving an assertion of functionality, rather than specifically checking the type the way an object oriented language would with a class hierarchy. For example,
```wdte
let example v => v {reflect 'Stream' => s.collect v};
```
works as a way to transparently convert streams into arrays and simply return all other types verbatim.
There's also a bit of a change to how …
=> all: Add Reflection

go.mod, go.sum, std/std.go, types.go
=> wdte: Move `Reflect()` to Make it Easier for Go to Use Directly

wdte_test.go
Thanks, https://github.com/golang/go/issues/28544#issuecomment-435401673. Had no idea that was there. Neat.
=> wdte: use `t.Helper()` during testing

ast/ast.go, go.mod, go.sum, scanner/scanner.go, scanner/scanner_test.go, scanner/token.go, scanner/util.go, wdte.go, wdte_test.go
Macros are handled at the scanner level in much the same way that is specified in #178. Unlike in there, however, the syntax uses `@` to specify a macro, rather than `!`. This is primarily to avoid ambiguity with the `!` function in the standard library, and also because `@` is the key used in Vim to replay a macro, although that's obviously a very different type of macro.
=> multiple: Add Macros

cmd/wdte/import.go, cmd/wdte/wdte.go
This might not work quite right. It seems to keep returning `(devel)` for the WDTE version for some bizarre reason. Probably just need to build it using `go get` or something.
=> cmd/wdte: Add version info.

std/std.go, types.go, wdte.go, wdte_test.go
Also updates some built-in types to support the new system.
Hmmm... Maybe it should handle strings, too...
=> std: rename `sub` to `set` and genericize

go.mod, std/stream/middle.go, std/stream/start.go, std/stream/stream.go, types.go, wdte_test.go
The old behavior of not returning the initial value from the stream can be replicated by just using `new ... -> skip 1`.
=> std/stream: Add `skip` and change `new`.
