std/std.go

std: Add Greater() to map.

---

std/stream/end.go
std/stream/start.go
std/stream/stream.go
wdte_test.go

Add `concat` and `any`. Part of #5.

std/stream: Add a few more functions.

---

std/stream/end.go
std/stream/stream.go
wdte_test.go

std/stream: Some more functions.

---

types.go
wdte_test.go

Possibly temporary solution to #23.

wdte: Make arrays evaluate their elements.

---

std/stream/middle.go
std/stream/stream.go
types.go
wdte_test.go

In testing flatMap, I seem to have hit a bug in the array
implementation. It's possible that arrays will need to keep track of the
frame they were created in. Maybe some FramedFuncs can fix it.
Waiting on #23.

std/stream: Add `flatMap`.

---

std/std.go
std/strings/strings.go
wdte_test.go

std/string: Add.

---

std/strings/format.go
std/strings/strings.go
wdte_test.go

std/strings: Add some more functions.

---

std/arrays/arrays.go
std/std.go
std/stream/start.go
wdte_test.go

std/arrays: Add.

---

std/stream/middle.go
std/stream/stream.go
wdte_test.go

std/stream: Add `enumerate`.

---

std/arrays/arrays.go
std/io/file/file.go
std/io/io.go
std/math/math.go
std/std.go
std/stream/end.go
std/stream/middle.go
std/stream/start.go
std/strings/format.go
std/strings/strings.go
wdte.go

Although this is technically part of #53, this part of it doesn't contain any changes to the grammar.

wdte: Overhaul scope internals.

---

ast/ast_test.go
std/strings/strings.go
wdte.go
wdte_test.go

Also fix a few linter warnings in a few different packages.

wdte: Add way to get list of variables in scope.

---

repl/repl.go
repl/repl_test.go

repl: Add basic implementation.

---

repl/example_repl_test.go
repl/repl.go

repl: Partial expression detection.

---

cmd/wdte/file.go
cmd/wdte/stdin.go
cmd/wdte/wdte.go

wdte/cmd: Basic implementation.

---

repl/examples_test.go
repl/repl.go
std/arrays/arrays.go
std/std.go
std/strings/strings.go
types.go
wdte.go
wdte_test.go

Affects #6, #26, and probably a few other ones, too.

multiple: A bunch of cleanups, tweaks, and a few actual features, too.

---

cmd/wdte/README.md
cmd/wdte/import.go
cmd/wdte/import_linux.go
cmd/wdte/import_other.go
cmd/wdte/stdin.go
cmd/wdte/wdte.go
repl/example_repl_test.go

cmd/wdte: Fix some API breakage. Add file system imports and documentation.

---

cmd/wdte/wdte.go

cmd/wdte: Add arguments to usage message.

---

translate.go
wdte.go

Also fixed `switch` expressions, so... Fixes #81.

wdte: Chains are now iterative. Same functionality, but less recursion.

---

cmd/wdte/README.md
cmd/wdte/import.go
cmd/wdte/import_linux.go
wdte.go
wdte_test.go

* wdte: Change behavior of lower bounds and `Known()`.
* cmd/wdte: Add ability to import plugins.
* cmd/wdte: Bind scope of imported scripts.

multiple: Some changes to scopes and module loading.

---

wdte.go
wdte_test.go

wdte: Subscope the scope of subscoped expressions to the surrounding scope.

---

cmd/wdte/import.go
cmd/wdte/stdin.go
go.mod
go.sum
repl/repl.go
std/std.go
translate.go
wdte.go
wdte_test.go

multiple: Remove Scope Bounds

---

translate.go
wdte.go

wdte: Rename Expr to FuncCall

---

std/arrays/arrays.go
std/std.go
wdte_test.go

multiple: Add Array Appending and Sorting and a Function for Getting Keys from a Scope

---

go.sum
std/arrays/arrays.go

std/arrays: Support Error Returns from `less` when Sorting

---

std/arrays/arrays.go
std/io/file/file.go
std/io/io.go
std/stream/middle.go
std/stream/start.go
std/stream/stream.go
types.go
wdte.go

multiple: Implement `fmt.Stringer` for a Bunch of Types

---

go.mod
go.sum
types.go

wdte: Add String() Method to Number

---

std/stream/middle.go
std/stream/start.go

No functionality changes. I just thought this would be a bit easier to deal with because everything's self-contained, and it's easier to see how the calling order in WDTE corresponds to the order in which the pieces of the Go implementation is called.

std/stream: Remove Extra Types in Favor of Nested Closures

---

README.md
wdte.go
wdte_test.go

Also, add `String()` method to `FuncCall`.

wdte: Update to Awesome-Go Standards

---

auto/auto.go
auto/func.go
auto/func_test.go
go.mod
go.sum

auto: Add FromFunc and Support for Function Arguments

---

wdte.go

wdte: Don't exit a Compound when an error is assigned using a `let`.

---

go.mod
go.sum
std/stream/end.go
std/stream/stream.go
wdte_test.go

std/stream: add `Extent()` and tweak `Drain()`

---

std/stream/end.go
wdte_test.go

std/stream: fix `Extent()` and allow negative sizes

---

go.mod
go.sum
wdte.go
wdte_test.go

wdte: Don't Ignore Errors in Ignored Chain Sections

---

std/all/all.go
std/all/gen.bash
std/all/gen.go

I noticed that `rand` was missing, so...

std/all: Generate list.

---

std/stream/middle.go
std/stream/stream.go
wdte_test.go

std/stream: add `zip`

---

types.go
wdte_test.go

wdte: fix comparison of floats
